version: "3"

networks: 
  laravel:

services: 
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
      - "80:80"
    volumes: 
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql 
    networks: 
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - "3306:3306"

    environment: 
      MYSQL_DATABASE: doozo
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: '#Virtualechos456'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    depends_on:
      - mysql
    ports:
      - 8081:80
    networks:
      - laravel

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports: 
      - "9090:9090"
    networks: 
      - laravel
